export const products = [
  {
    id: 1,
    title: "Artist / Academic's website & blog",
    desc: "Personal website",
    techs: [
      "JS ",
      "NodeJS ",
      "MongoDB ",
      "Mongoose ",
      "Atlas ",
      "Express ",
      "React ",
      "Heroku ",
      "Git ",
      "Github ",
      "Cloudinary ",
      "EmailJS ",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655149324/manuel/marisela_hj00nt.png",
    linkGit: "https://github.com/Manuelhh/marisela-website",
    linkApp: "https://mariselalfierro.herokuapp.com/",
  },
  {
    id: 2,

    title: "OK200 Web Programmer",
    desc: "Provides software updates to electronic instruments",
    techs: [
      "HTML",
      "CSS",
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "React",
      "Typescript",
      "SASS",
      "Git",
      "Github",
      "Cloudinary",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1669734791/manuel/Screen_Shot_2022-11-29_at_10.12.57_AM_yktoik.png",
    linkGit: "https://github.com/scottc11/ok-web-programmer",
    linkApp: "https://github.com/scottc11/ok-web-programmer",
  },
  {
    id: 3,
    title: "Applants",
    desc: "An IG like web application",
    techs: [
      "HTML",
      "CSS",
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "Heroku",
      "Git",
      "Github",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038101/manuel/applants_xbwao1.png",
    linkGit: "https://github.com/Manuelhh/applants",
    linkApp: "https://applants.herokuapp.com",
  },
  {
    id: 4,
    title: "Yelpcamp",
    desc: "A Yelp like web application for campsites",
    techs: [
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "Heroku",
      "Git",
      "Github",
      "Location services",
      "Map Serivices",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655038544/manuel/yelpcamp_lispaw.png",
    linkGit: "https://github.com/Manuelhh/yelpcamp-app",
    linkApp: "https://mh-yelpcamp.herokuapp.com/",
  },
  {
    id: 5,
    title: "Public API",
    desc: "An application programming interface made publicly available for software developers",
    techs: [
      "JS",
      "NodeJS",
      "MongoDB",
      "Mongoose",
      "Atlas",
      "Express",
      "Heroku",
      "Git",
      "Github",
    ],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655041118/manuel/api_jp41gw.webp",
    linkGit: "https://github.com/Manuelhh/API-dogs",
    linkApp: "https://github.com/Manuelhh/API-dogs",
  },
  {
    id: 6,
    title: "Hangman",
    desc: "Classic Hangman game",
    techs: ["HTML", "CSS", "JS", "Github Pages", "Git", "Github"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655040269/manuel/Screen_Shot_2022-06-12_at_9.24.13_AM_ox2wg8.png",
    linkGit: "https://github.com/Manuelhh/hangman",
    linkApp: "https://optimistic-northcutt-494969.netlify.app",
  },
  {
    id: 7,
    title: "Connect Four",
    desc: "Classic Connect Four game",
    techs: ["HTML", "CSS", "JS", "Netlify", "Git", "Github"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037011/manuel/connectFour_rqb0fo.png",
    linkGit: "https://github.com/Manuelhh/connect-four",
    linkApp: "https://cocky-goodall-e34f0c.netlify.app",
  },
  {
    id: 8,
    title: "Movie Fight",
    desc: "Compares two given movies collecting data from a pulic API",
    techs: ["HTML", "CSS", "JS", "Netlify", "Git", "Github", "axios", "JSON"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037769/manuel/movieFight_nrycmy.png",
    linkGit: "https://github.com/Manuelhh/movie-fight-app",
    linkApp: "https://superlative-bunny-0d9bb2.netlify.app",
  },

  {
    id: 9,
    title: "HTML & CSS based website",
    desc: "A website created using only HTML and CSS",
    techs: ["HTML", "CSS", "Netlify", "Git", "Github"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037938/manuel/website_efsv77.png",
    linkGit: "https://github.com/Manuelhh/html-css-website",
    linkApp: "https://competent-easley-7a403a.netlify.app",
  },

  {
    id: 10,
    title: "Timer",
    desc: "Interactive timer app",
    techs: ["HTML", "CSS", "JS", "Github Pages", "Git", "Github"],
    img: "https://res.cloudinary.com/mangud/image/upload/v1655037217/manuel/timerApp_kprfnv.png",
    linkGit: "https://github.com/Manuelhh/timer-app",
    linkApp: "https://manuelhh.github.io/timer-app/",
  },
];
